### ISSUE TITLE
[wiki] Dead link "How To Get Anaconda" in wiki page "The GDMC Framework"

### ISSUE THREAD

**Issue by nikigawlik** [mcgreentn/MCAI#4]
In the "The GDMC Framework" page in the wiki: https://github.com/mcgreentn/GDMC/wiki/The-GDMC-Framework
in the section "First steps" the link "How To Get Anaconda" is dead (points to a "page does not exist" page).

I am assuming the correct URL is this: 
https://conda.io/projects/conda/en/latest/user-guide/install/index.html

As far as I am aware, I cannot make a pull request to fix this, so I made an issue instead. It would be nice if someone could update the page.

**Comment by mcgreentn** [comment]
Thank you for pointing this out! I just fixed it
